const responseCodes = {
    BROWSER_INITIATED: 'BROWSER_INITIATED',
    BROWSER_INITIATION_FAILED: 'BROWSER_INITIATION_FAILED',
    BROWSER_CLOSED: 'BROWSER_CLOSED',
    BROWSER_CLOSING_FAILED: 'BROWSER_CLOSING_FAILED',
    RECAPTCHA_FOUND: 'RECAPTCHA_FOUND',
    RECAPTCHA_SOLVED: 'RECAPTCHA_SOLVED',
    RECAPTCHA_SOLVING_FAILED: 'RECAPTCHA_SOLVING_FAILED',
    TOTAL_RESULTS_COUNT: 'TOTAL_RESULTS_COUNT',
    NO_RESULTS_FOUND: 'NO_RESULTS_FOUND',
    INDIVIDUAL_LINKS_PAGE_SCRAPED: 'INDIVIDUAL_LINKS_PAGE_SCRAPED',
    INDIVIDUAL_LINKS_PAGE_SCRAPING_FAILED:
        'INDIVIDUAL_LINKS_PAGE_SCRAPING_FAILED',
    PROXY_AUTHENTICATION_SUCCEED: 'PROXY_AUTHENTICATION_SUCCEED',
    PROXY_AUTHENTICATION_FAILED: 'PROXY_AUTHENTICATION_FAILED',
    INDIVIDUAL_ENTITY_SCRAPED: 'INDIVIDUAL_ENTITY_SCRAPED',
    INDIVIDUAL_ENTITY_SCRAPING_FAILED: 'INDIVIDUAL_ENTITY_SCRAPING_FAILED',
}

export default responseCodes
